import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hotel-brand-franchise-fee-audit",
  "engine": "recovery",
  "title": "Hotel Brand & Franchise Fee Audit",
  "shortTitle": "Hotel Brand and Franchise Fee Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through hotel brand & franchise fee audit",
  "industry": "Hotel Ownership Financial Assurance",
  "uiPort": 4619,
  "apiPort": 5619,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Hotel Brand & Franchise Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Brand Charged Fees",
    "expectedLabel": "Agreement-Supported Fees",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Hotel Brand & Franchise Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("franchise-agreement-library","HBF01","Franchise agreement library","Execute franchise agreement library using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed franchise agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Franchise agreement library Reference","text","HBF01-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("property-room-registry","HBF02","Property room registry","Execute property room registry using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed property room registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Property room registry Reference","text","HBF02-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("pms-revenue-ingestion","HBF03","PMS revenue ingestion","Execute pms revenue ingestion using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed pms revenue ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","PMS revenue ingestion Reference","text","HBF03-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("gross-room-revenue-definition","HBF04","Gross room revenue definition","Execute gross room revenue definition using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed gross room revenue definition decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Gross room revenue definition Reference","text","HBF04-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("royalty-calculation","HBF05","Royalty calculation","Execute royalty calculation using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed royalty calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Royalty calculation Reference","text","HBF05-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("marketing-assessment-audit","HBF06","Marketing assessment audit","Execute marketing assessment audit using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed marketing assessment audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Marketing assessment audit Reference","text","HBF06-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("reservation-fee-validation","HBF07","Reservation fee validation","Execute reservation fee validation using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed reservation fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Reservation fee validation Reference","text","HBF07-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("loyalty-program-fee-audit","HBF08","Loyalty program fee audit","Execute loyalty program fee audit using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed loyalty program fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Loyalty program fee audit Reference","text","HBF08-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("technology-system-fees","HBF09","Technology system fees","Execute technology system fees using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed technology system fees decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Technology system fees Reference","text","HBF09-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("opening-renovation-charges","HBF10","Opening renovation charges","Execute opening renovation charges using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed opening renovation charges decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Opening renovation charges Reference","text","HBF10-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("exclusion-validation","HBF11","Exclusion validation","Execute exclusion validation using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed exclusion validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Exclusion validation Reference","text","HBF11-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("brand-invoice-reconciliation","HBF12","Brand invoice reconciliation","Execute brand invoice reconciliation using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed brand invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Brand invoice reconciliation Reference","text","HBF12-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("brand-dispute-workflow","HBF13","Brand dispute workflow","Execute brand dispute workflow using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed brand dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Brand dispute workflow Reference","text","HBF13-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("credit-recovery","HBF14","Credit recovery","Execute credit recovery using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed credit recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Credit recovery Reference","text","HBF14-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]}),
feature("property-brand-economics","HBF15","Property brand economics","Execute property brand economics using franchise and management agreements, properties, PMS revenue, room revenue definitions, royalties, marketing, reservations, loyalty, technology, openings, renovations, invoices, and credits.","Produce a governed property brand economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Brand / Hotel Property","text","Brand / Hotel Property · Standard Case"],["caseReference","Property brand economics Reference","text","HBF15-2026-001"],["chargedAmount","Brand Charged Fees","currency",938000],["supportedAmount","Agreement-Supported Fees","currency",806680],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Franchise agreement library case","Property room registry case","PMS revenue ingestion case","Gross room revenue definition case","Royalty calculation case"]})
]);
